language: go

go:
  - 1.9
  - master

matrix:
  allow_failures:
    - go: master

before_install:
  - go get -t -v ./...

script:
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
